### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by olback** [olback/tempfiles-rs#1]
* [x] Error template
* [x] Api Docs (OpenAPI w/ [GREsau/okapi](https://github.com/GREsau/okapi))
* [x] ShareX config
* [x] Make the actual thing
* [x] Version link to commit
* [x] `pg_cron`
* [x] Run the server from `docker-compose.yml`
* [ ] File drag-and-drop https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/
* [x] SEO (Open graph?)
* [x] ShareX tab
* [x] Click to copy url
